import type { Lang } from '../types'

/**
 * Every word the deck shows, per language. A new language is one more entry here and one more script in
 * `detectLanguage`. Station names, checklist items and `moku` stay as the rails spell them: they are names.
 */
const WORDS = {
  en: {
    tabs: { flow: 'Flow', ideas: 'Ideas', tests: 'Tests' },
    opened: 'moku deck opened.',
    sample: 'Sample data. This directory has no moku session, so this is how a game change would look.',
    noChange: 'No open change. The rails are clear for new work.',
    kind: (type: string, size: string, isGame: boolean) => `${isGame ? 'game ' : ''}${type}, size ${size}`,
    here: 'you are here',
    nextUp: 'next',
    showMore: (left: number) => `Show ${left} more`,
    newest: (shown: number, all: number) => `The newest ${shown} of ${all}`,
    beforeClose: 'Before it can close',
    waits: 'Waits for you',
    paused: 'The station is paused.',
    approve: 'Approve and continue',
    approveSay: 'approved, continue',
    discuss: 'Discuss first',
    discussFill: 'Before you continue: ',
    go: 'Continue',
    goSay: 'continue with the next step',
    where: 'Where are we',
    whereSay: 'where are we, and what is next',
    testsLine: (repeats: number, slow: number) => `${repeats} test runs were not needed, ${slow} tests are slow`,
    openTests: 'Open tests',
    ideasEmpty: 'Nothing is parked. Tell Claude to park an idea and it waits here until you start it.',
    other: 'other',
    start: 'Start',
    startSay: (idea: string) => `let us start the parked idea: ${idea}`,
    remove: 'Remove',
    removeSay: (idea: string) => `remove the parked idea: ${idea}`,
    noRuns: 'No test run is logged yet.',
    allNeeded: (runs: number) => `All ${runs} test runs were needed.`,
    wasted: (repeats: number, runs: number, seconds: number) => `${repeats} of ${runs} test runs were not needed. ${seconds}s wasted.`,
    split: (needed: number, repeats: number) => `${needed} needed, ${repeats} repeated a green run with no edit between`,
    noSlow: 'No slow tests.',
    slow: 'Slow tests',
    barHint: 'The bar is the time one test takes.',
    speedUp: 'Speed up the slow tests',
    speedUpSay: 'show the slow tests and propose how to speed them up',
    on: 'On',
    off: 'Off',
    coach: 'Tell agents when they repeat a run',
    coachOn: 'An agent that repeats a green run is told to read the saved output instead.',
    coachOff: 'Repeats are only counted.',
    session: 'This session',
    notNeeded: 'not needed',
    red: 'red',
    done: 'done',
    mustDo: 'must do',
    optional: 'optional',
    needed: 'needed',
    hideItems: 'Hide the items',
    pickFrom: (items: number) => `Pick from ${items} items`,
    picked: 'Picked',
    pick: 'Pick',
    status: (who: string, what: string, isRunning: boolean) => `${who} ${isRunning ? 'is' : 'was'} ${what}`,
    more: (others: number) => `, ${others} more at work`,
    who: (name: string) => name,
    testsRed: 'Tests red',
    testsGreen: 'Tests green',
    took: (summary: string, seconds: number) => (summary === '' ? `${seconds}s` : `${summary} in ${seconds}s`),
    rowNotNeeded: 'Not needed: nothing was edited since the last green run',
    describeIn: '',
    details: 'Details',
    sendingNow: (text: string) => `Sending: ${text}`,
    less: 'Less',
    digesting: 'Writing short cards for the ideas…',
  },
  ru: {
    tabs: { flow: 'Маршрут', ideas: 'Идеи', tests: 'Тесты' },
    opened: 'moku deck открыт.',
    sample: 'Пример данных. В этой папке нет moku-сессии. Так выглядела бы работа над игрой.',
    noChange: 'Открытых изменений нет. Рельсы свободны для новой работы.',
    kind: (type: string, size: string, isGame: boolean) => `${isGame ? 'игра, ' : ''}${type}, размер ${size}`,
    here: 'вы здесь',
    nextUp: 'дальше',
    showMore: (left: number) => `Показать ещё: ${left}`,
    newest: (shown: number, all: number) => `Последние ${shown} из ${all}`,
    beforeClose: 'До закрытия осталось',
    waits: 'Ждёт вас',
    paused: 'Станция на паузе.',
    approve: 'Одобрить и продолжить',
    approveSay: 'одобрено, продолжай',
    discuss: 'Сначала обсудить',
    discussFill: 'Прежде чем продолжить: ',
    go: 'Продолжить',
    goSay: 'продолжай со следующего шага',
    where: 'Где мы',
    whereSay: 'где мы сейчас и что дальше',
    testsLine: (repeats: number, slow: number) => `Лишних прогонов тестов: ${repeats}, медленных тестов: ${slow}`,
    openTests: 'Открыть тесты',
    ideasEmpty: 'Отложенных идей нет. Попросите Claude отложить идею, и она будет ждать здесь.',
    other: 'прочее',
    start: 'Начать',
    startSay: (idea: string) => `давай начнём отложенную идею: ${idea}`,
    remove: 'Удалить',
    removeSay: (idea: string) => `удали отложенную идею: ${idea}`,
    noRuns: 'Прогонов тестов в логе пока нет.',
    allNeeded: (runs: number) => `Все прогоны тестов были нужны: ${runs}.`,
    wasted: (repeats: number, runs: number, seconds: number) => `Лишних прогонов тестов: ${repeats} из ${runs}. Потеряно ${seconds} с.`,
    split: (needed: number, repeats: number) => `Нужных: ${needed}. Повторили зелёный прогон без правок: ${repeats}`,
    noSlow: 'Медленных тестов нет.',
    slow: 'Медленные тесты',
    barHint: 'Полоска показывает время одного теста.',
    speedUp: 'Ускорить медленные тесты',
    speedUpSay: 'покажи медленные тесты и предложи, как их ускорить',
    on: 'Вкл',
    off: 'Выкл',
    coach: 'Сообщать агентам о повторном прогоне',
    coachOn: 'Агент, повторивший зелёный прогон, получит совет читать сохранённый вывод.',
    coachOff: 'Повторы только считаются.',
    session: 'Эта сессия',
    notNeeded: 'лишний',
    red: 'красный',
    done: 'пройдено',
    mustDo: 'обязательно',
    optional: 'по желанию',
    needed: 'нужный',
    hideItems: 'Скрыть пункты',
    pickFrom: (items: number) => `Выбрать из пунктов: ${items}`,
    picked: 'Выбран',
    pick: 'Выбрать',
    status: (who: string, what: string, isRunning: boolean) => (isRunning ? `${who}: ${what}` : `${who}, готово: ${what}`),
    more: (others: number) => `, ещё работают: ${others}`,
    who: (name: string) => name.replace(/^Agent /, 'Агент '),
    testsRed: 'Тесты красные',
    testsGreen: 'Тесты зелёные',
    took: (summary: string, seconds: number) => (summary === '' ? `${seconds} с` : `${summary} за ${seconds} с`),
    rowNotNeeded: 'Лишний: после зелёного прогона ничего не правилось',
    describeIn: 'The person follows your work in Russian. Write the `description` of every Bash call in Russian.',
    details: 'Подробнее',
    sendingNow: (text: string) => `Отправляю: ${text}`,
    less: 'Свернуть',
    digesting: 'Пишу короткие карточки для идей…',
  },
}

export type Words = (typeof WORDS)['en']

/**
 * The words of one language.
 *
 * @example
 * words('ru').tabs.ideas // 'Идеи'
 */
export function words(lang: Lang): Words {
  return WORDS[lang] ?? WORDS.en
}
